Host: localhost
LinksUseHttps: true
SiteTitle: Title of the blog
SiteDescription: "Cool blog to do cool stuff 1, cool stuff 2 and so on..."
Copyright: => @$"All articles © {DateTime.Now.Year} James D. Author"
GenerateSearchIndex: true